import React from 'react';
import { motion } from 'motion/react';

export default function TermsOfService() {
  return (
    <main className="overflow-x-hidden bg-white px-6 pb-24 pt-32 sm:px-8 sm:pt-40 md:pt-48">
      <div className="mx-auto max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        >
          <h1 className="font-display text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-slate-500">Last updated: 12/09/2026</p>

          <div className="mt-12 space-y-10 text-sm leading-relaxed text-slate-600 sm:text-[15px]">
            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">1. Acceptance of Terms</h2>
              <p className="mt-3">
                By accessing or using the ARETEUS website, the ARETEUS App, or the ARETEUS Patch
                device (together, our &quot;services&quot;), you agree to be bound by these Terms of
                Service. If you do not agree to all of these terms, do not use our services.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">2. Eligibility</h2>
              <p className="mt-3">
                You must be at least 18 years old to create an account or use the App and Patch
                device. By creating an account, you confirm that you are 18 or older.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">3. Use of Services</h2>
              <p className="mt-3">
                You agree to use our services only for lawful purposes and in a way that does not
                infringe the rights of, restrict, or inhibit anyone else&apos;s use and enjoyment of
                the services.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">
                4. Not a Medical Device; Not Medical Advice
              </h2>
              <p className="mt-3 font-medium text-slate-900">
                This is important, please read it carefully.
              </p>
              <p className="mt-4">
                The ARETEUS Patch and App are wellness tools, not medical devices. They are not
                intended to diagnose, treat, cure, or prevent any disease or medical condition, and
                are not a substitute for professional medical advice, diagnosis, or treatment. The
                Patch and App are not currently intended for use by, or under the supervision of,
                licensed clinicians as part of patient care.
              </p>
              <p className="mt-4">
                Metrics shown in the App (including heart rate, SpO2, respiration rate, HRV, and
                recovery/readiness scores) are estimates generated by consumer-grade sensors and
                algorithms, and may be inaccurate or incomplete.
              </p>
              <p className="mt-4 font-medium text-slate-900">
                Never disregard professional medical advice or delay seeking it because of something
                you saw in the App. If you think you may have a medical emergency, call your local
                emergency number immediately — do not rely on the App or Patch device.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">5. AI Coach</h2>
              <p className="mt-3">
                The App includes an AI Coach feature that uses an AI model (currently Google Gemini)
                to generate conversational responses and automated insight summaries based on your
                data. These responses are generated by AI, may be incomplete, generic, or incorrect,
                and do not constitute medical advice. You are responsible for using your own
                judgment, and consulting a qualified professional, before acting on anything the AI
                Coach tells you.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">
                6. Purchases and Payments
              </h2>
              <p className="mt-3">
                All purchases made through our website are subject to availability. We reserve the
                right to refuse or cancel any order for any reason. Payments are processed through
                Stripe, and you agree to provide current, complete, and accurate purchase and
                account information for all purchases.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">
                7. Shipping and Delivery
              </h2>
              <p className="mt-3">
                Shipping times are estimates and not guaranteed. ARETEUS is not responsible for
                delays caused by shipping carriers or customs. Risk of loss and title for items
                purchased from ARETEUS pass to you upon delivery of the items to the carrier.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">8. Your Account</h2>
              <p className="mt-3">
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activity that occurs under your account. Notify us immediately at the
                contact address below if you believe your account has been accessed without your
                authorization.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">
                9. Intellectual Property
              </h2>
              <p className="mt-3">
                The content on our website and in our App, including text, graphics, logos, and
                images, is the property of ARETEUS and is protected by copyright and other
                intellectual property laws. You may not use any of our intellectual property without
                our prior written consent.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">
                10. Limitation of Liability
              </h2>
              <p className="mt-3">
                To the fullest extent permitted by law, ARETEUS shall not be liable for any
                indirect, incidental, special, consequential, or punitive damages, or any loss of
                profits, revenues, data, or goodwill, arising from your use of our services —
                including any health, wellness, or lifestyle decisions you make based on data,
                insights, or AI Coach responses shown in the App.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">11. Governing Law</h2>
              <p className="mt-3">
                These Terms of Service shall be governed by and construed in accordance with the
                laws of the jurisdiction in which ARETEUS operates, without regard to its conflict
                of law provisions.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">12. Changes to Terms</h2>
              <p className="mt-3">
                We reserve the right to modify these Terms of Service at any time. We will notify
                you of any changes by posting the new terms on this page. Your continued use of our
                services after such changes constitutes your acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-slate-900">13. Contact Us</h2>
              <p className="mt-3">
                If you have any questions about these Terms of Service, please contact us at{' '}
                <a
                  href="mailto:info@areteus.us"
                  className="font-medium text-slate-900 underline underline-offset-2 hover:text-slate-600"
                >
                  info@areteus.us
                </a>
                .
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </main>
  );
}
